name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo check --all

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['26.0', '27.0', '28.0']
        toolchain: [stable]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo test --all

  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }}
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all -- -D warnings

